### ISSUE TITLE
Cant install plex home theater

### ISSUE THREAD

**Issue by jonbitzen** [ProfessorKaos64/SteamOS-Tools#106]
I followed the instructions on the website here first to install web apps:

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Web-Apps

Subseqently I tried to install Plex Home Theater using the following command:

sudo apt-get install plexhometheater

Now I get a message "E: Unable to localte package plexhometheater"

I tried to do sudo apt-get update to force the package repository to reload, but I got the same result after attempting again to install PHT.

This worked only a week or two ago.  I recently updated my SteamOS-Tools checkout to get the web apps fix.

Is PHT no longer in the repo, or is there some issue with SteamOS-Tools that was introduced since I updated?

BTW thanks for the webapp fix, Netflix and Spotify live again on my steam machine :)

Thanks,

jonbitzen

**Comment by ProfessorKaos64** [comment]
I removed that package because it was problematic. Rebuilding didn't work that well. It was found a community driven fork is continuing work, called OpenPHT. Please subscribe and follow the issues ticket already available: #104 . After a bit more testing, I will release it to brewmaster, and take it out of brewmaster_testing.
