### ISSUE TITLE
Playonlinux : Error with   /var/cache/apt/archives/libattr1_1%3a2.4.47-2+bsos3_i386.deb

### ISSUE THREAD

**Issue by silelmot** [ProfessorKaos64/SteamOS-Tools#118]
When trying to install Playonlinux i get following error:

Trigger für man-db (2.7.0.2-5+bsos3) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/libattr1_1%3a2.4.47-2+bsos3_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

SteamOS is a fresh install. Debainrepos are added. Beta Updates are installed. :/

**Comment by ProfessorKaos64** [comment]
https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Troubleshooting#i-cant-install-package_name-after-adding-the-extra-repositories

**Comment by silelmot** [comment]
Thx. Works

**Comment by silelmot** [comment]
Installation worked now but cant still not start it at steam big picture mode

**Comment by ProfessorKaos64** [comment]
You won't be able to start playonlinux in big picture mode. A lot of applications have issues running in SteamOS big picture mode due to various issues (scaling, only running on program at a time, application design). If  you are trying to run a Windows game on SteamOS in BPM, one of the few ways you may be able to do this is with the instructions linked below. This is not an issue with SteamOS-Tools, as PlayOnLinux is a Debian application, and even if it were package into my repository, it would be out of my control. There are tricks to present the window with Xephyr, as does the web apps function here, but that has limitations. Such a trick does not work with the new Itch.io client.

https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Playing-Steam-(Windows)-Games-Using-PlayOnLinux
