### ISSUE TITLE
Issue with setting up webapps on Chrome

### ISSUE THREAD

**Issue by alexofaao2000** [ProfessorKaos64/SteamOS-Tools#69]
Hey professorkaos64 You told me to contact you here. I've copied my comment from steam and pasted it here.

Ok so I followed your guide here, and it worked to get the icons to appear in big picture mode, but when I click on one it just loads to a black screen nothing more . I have tried my wired Xbox 360 controller and mouse and keyboard still just a black screen. I can move my mouse and it will show, but I can't  escape back to big picture mode, and I have to reset the system. Though When I switch to desktop mode however I can click on the app icons that where created, and they load into a windowed mode fine no issue. I checked your github page to see if maybe someone else came across this issue, but sadly I found nothing. 

Any idea on what I might have done wrong?

I'm just toying around with steamos for fun and wanted to see if I can replace my Xbox 360 with it if I get these apps to work right cause my gaming PC is in my basement

If you need images I can up load them later I'm currently on a iPad if it will help

**Comment by ProfessorKaos64** [comment]
I only have Nvidia GPU's at home, so I cannot test AMD, which I know has issues with desktop applications and desktop mode. Can you use desktop mode ok? I know this works fine on my test systems. It seems the Xephyr X window does load, but does not render right. I'll do my best to figure out what you have going here.

CPU?
GPU?
Is this a desktop/laptop?
Are you using dual graphics on a laptop if so?

**Comment by alexofaao2000** [comment]
Ok so it a very basic extra desktop system I have I use to run  Ubuntu on it. It I has  amd fm2+ board from gigabyte with a a10 6800 processor I have no GPU right now cause I was gonna go get a nvidia 750 ti just couldn't make up my mind on it . Do you really think it could be  non dedicated GPU issue. When I switch to desktop mode the apps it created from the process work and play fine. They just don't want run with big picture mode but I installed plex home theater  and that runs fine from desktop and big picture mode 

Sent from Yahoo Mail on Android

**Comment by ProfessorKaos64** [comment]
It's possible that it could be a integrated GPU problem, especially if it's AMD. I am not quite sure, but getting more help on this is tough since it is unique to SteamOS/Steam for Linux. Did you try this on a Steam client under a normal Linux distro? You could also link this issues ticket in the Steam Universe group under the "SteamOS" subgroup. I am there very frequently, but perhaps someone there can help unravel this for you. If you do get an Nvidia GPU and try this again later, I'd be interested to see if you still have this issue. 

If SteamOS itself works fine, that's a tough one. Running `lspci -v` in desktop mode should report what kernel driver you are using for your integrated card as well. I wish I could test this, but my only AMD board is slightly out of commission.

Good that plex works. I just repackaged that for SteamOS brewmaster if that's what you used.

**Comment by alexofaao2000** [comment]
No I'm usein the original steamos would switching to the brewmaster version help my situation you think? 


Also thank you so much for responding to my questions.  I sometimes feel that Linux groups hate to help others out  sometimesometimes.   I mean like I said I used Ubuntu before but when I was new to it all I ever received was hate in forums and stuff. 

Sent from Yahoo Mail on Android

**Comment by ProfessorKaos64** [comment]
Possibly. If you do install the new version, and wish to keep downloaded games, choose the expert install and keep your /home partition. Otherwise a clean install entirely is best. Just keep in mind, I am unsure if this will fix your issue, but you will be better off for future updates, since Brewmaster is the latest and will likely land on Steam Machines come November. It is based on the newer and current Debian release, "Jessie." If you have issues with the new Steam beta client, you can unselect this in Settings > System.

If you need help creating a USB/DVD of SteamOS brewmaster, you could also try the [steamos-mega-downloader](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/SteamOS-Mega-Downloader) I made.

**Comment by ProfessorKaos64** [comment]
@alexofaao2000 , any update on your issue? Have you tried lately?

**Comment by ProfessorKaos64** [comment]
It should be noted that most DRM-protected content can now be accessed via the native SteamOS / BPM browser. Web apps will be decommissioned soon.
