### ISSUE TITLE
default pair-ps3-bluetooth script not working with brewmaster

### ISSUE THREAD

**Issue by ubergeek42** [ProfessorKaos64/SteamOS-Tools#89]
The script `utilities/pair-ps3-bluetooth.sh` doesn't quite work with the latest brewmaster(freshly installed from the oct 5 iso)

To make it work I made a few changes I want to document here for others(or maybe for inclusion into the script). The apt-get install lines didn't seem to work, and I'm not sure are needed. Sixpair seems to be part of qtsixa, so downloading and compiling manually probably isn't necessary either.

For my particular bluetooth adapter, I also had to set it to be discoverable by default. To do this I edited the /lib/udev/rules.d/50-bluetooth-hci-auto-poweron.rules to add “piscan” to the arguments for hciconfig in addition to “up". This makes my adapter become discoverable when connected. If you were to include this I suspect the edited file should be copied to /etc/udev/rules.d/ with the same name(I believe that overrides whatever is in /lib/udev/rules.d).

This was confirmed by typing `hciconfig` and seeing PSCAN ISCAN in addition to UP. If mine wasn't listing PSCAN/ISCAN then I wasn't able to connect my controllers.

With that done `sixpair` and `sixad` worked fine. The default mappings from sixad don't seem to work with steam though(and are just weird in general), but someone has made a wonderful fork that makes it act like an xbox360 controller, greatly improving compatibility. The script makes not of just editing the controller settings in steam, but that isn't present anymore(at least in mine, running the beta client). Downloading the source for this fork and compiling/installing made the controller work perfectly inside steam(though the dpad doesn't seem to work properly everywhere).

https://github.com/arcsur/qtsixa (Found from https://github.com/falkTX/qtsixa/pull/10 )

That fork does need a default configuration `/var/lib/sixad/profiles/default` that looks like the following to enable that mapping. I've also found that rumble support over bluetooth causes massive lag in some games(skyrim is what I tested with) so disabling rumble seems like it's probably a sane default as well. I saw some other reports of this lag online but was unable to find a solution.
```
enable_xpad_emulation 1
enable_rumble 0
```

Anyway, I hope this information is useful to someone.

**Comment by ProfessorKaos64** [comment]
Sure, I can start to review this and see what I can come up with. Do you mind linking to your configuration files? Yes, sixpair is part of qtsixa. Very interesting to see this fork. I have a podcast to record when I get home, but I should be able to check this out sometime this week and test around with it. Thank you very much. Should be able to fix up with tool with your help.

**Comment by ProfessorKaos64** [comment]
@ubergeek42 , could you please link your work in a GitHub gist/slexy paste, and/or attach files? I can fix this up. I could guess and tinker to get this working, but referencing your files would be the most accurate.

**Comment by ubergeek42** [comment]
Hey, sorry I didn't get back to you sooner. There isn't much to attach or post, it was just the two files:
`/lib/udev/rules.d/50-bluetooth-hci-auto-poweron.rules` adding piscan after hciconfig up (I seem to recall this is just a one or two line file.

`/var/lib/sixad/profiles/default` to have the xpad_emulation and rumble options set.
There's still the issue with the dpad not being functional, and I wasn't able to come up with a solution. I suspect some of the mappings in that fork are off.

**Comment by ProfessorKaos64** [comment]
Ok, i'll try to fix this up this week

**Comment by JickJant** [comment]
Hi there, this is more just for your information. I also run into some issues regarding the PS3 controller connection by bluetooth, but only after the installation. It might be that SteamOS Brewmaster has some problem with the sixad program, at least in Ubuntu has, please see discussion thread (https://bugs.launchpad.net/ubuntu/+source/bluez/+bug/1449080). It might be linked to the new BlueZ version, but they pushed it back. To apply their solution helped me out, so maybe interesting for you.

**Comment by ProfessorKaos64** [comment]
Ok, i'll take a look, thank you very much @JickJant. I'll likely try to fix this up and look at DS4/PS4 controller pairing soon as well.

**Comment by ProfessorKaos64** [comment]
The forked QTSixa you linked was built and packaged to the Libregeek repository. I updated the pair-ps3-bluetooth script with the appropriate systemctl commands for the sixad service. I added the required packages as dependencies in the build to allow full use from desktop mode as well. 

I have not yet corrected the dpad mappings. I found that for some reason, when I start sixad, it robs the execute bit from `/usr/lib/bluetooth/bluetoothd`, possibly due to some faulty old SysV-style code that systemd hooks into for managing the service. As a cruddy "hack," I correct the permissions after starting it.

Before (755):
```
-rwxr-xr-x 1 root root 980000 May  8 16:56 /usr/lib/bluetooth/bluetoothd
```

After (611):
```
-rw-r--r-- 1 root root 980000 May  8 16:56 /usr/lib/bluetooth/bluetoothd
```

Sometimes enabling execute and restarting the bluetooth service let's me connect, but sometimes not. I need to nail down a process. I can attest that once paired, my controller will connect after a reboot fine.

**Comment by JickJant** [comment]
Hi, thanks a lot for your work so far. Unfortunately, I will be only able
to test and check end of this /beginning of next week. Will get back to you
then.
Cheers

The forked QTSixa you linked was built and packaged to the Libregeek
repository. I updated the pair-ps3-bluetooth script with the appropriate
systemctl commands for the sixad service. I added the required packages as
dependencies in the build to allow full use from desktop mode as well.

I have not yet corrected the dpad mappings. I found that for some reason,
when I start sixad, it robs the execute bit from
/usr/lib/bluetooth/bluetoothd, possibly due to some faulty old SysV-style
code that systemd hooks into for managing the service. As a cruddy "hack,"
I correct the permissions after starting it.

Before (755):

-rwxr-xr-x 1 root root 980000 May  8 16:56 /usr/lib/bluetooth/bluetoothd

After (611):

-rw-r--r-- 1 root root 980000 May  8 16:56 /usr/lib/bluetooth/bluetoothd

Sometimes enabling execute and restarting the bluetooth service let's me
connect, but sometimes not. I need to nail down a process. I can attest
that once paired, my controller will connect after a reboot fine.

—
Reply to this email directly or view it on GitHub
<https://github.com/ProfessorKaos64/SteamOS-Tools/issues/89#issuecomment-151707646>
.

**Comment by ProfessorKaos64** [comment]
@JickJant any update? I actually paired a controller last night using this script off a fresh install of Brewmaster.

**Comment by JickJant** [comment]
No, not really. I have tried through an schroot environment (wheezy base), but running into issues between the jessie and wheezy base. I then tried ps3joy from ROS, but their jade distribution for Debian Jessie is still work in progress. I will reinitiated my system this weekend and retry your skript.

**Comment by ProfessorKaos64** [comment]
Ok, thank you. If you come across any other tools that work, I will attempt to package them (if they do not exist in Jessie).

**Comment by ProfessorKaos64** [comment]
On an interesting note, I think I am going to try and shim in systemd support, based on what the Arch Linux folks do. If I do though, it will only be in the testing repo for a bit until I can verify it.

**Comment by jhermsdorf** [comment]
I did a fresh install of the latest brewmaster version 2.60 (https://steamcommunity.com/groups/steamuniverse/discussions/1/458606248615748046/) and now installation of 'sixad' via package manager seems to be broken.

pair-ps3-bluetooth.sh gives errors that /etc/init.d/sixad doesn't exist, as well as /var/lib/sixad. And the command 'sixpair' could be found.

**Comment by ProfessorKaos64** [comment]
sixpair is installed via qtsixa, which is part of my [repository](http://packages.libregeek.org/SteamOS-Tools/pool/main/q/qtsixa/). Additionally, this script is kinda-works, as I've been able to pair my controllers just fine with it, but I know it not a consistent fool for everyone and needs to be improved. You _can_ pair PS3 controllers in the same way you do with PS4 controllers on SteamOS under desktop mode. It acts like it wants a code, but if you wrestle with it enough, it connects.

**Comment by ProfessorKaos64** [comment]
You may be in luck (now or soon):

**Comment by pogipants** [comment]
I am getting the same error as @jhermsdorf , did either of you get this resolved? Should I try to fix qtsixa or use the SteamOS interface for the PS3 controller?

**Comment by ProfessorKaos64** [comment]
I was able to make this work in the past, so i'm not sure. I still keep it around regardless. The client now can pair PS3 Controllers, so you shouldn't be using this script anymore over that. I'll update the Valve wiki with some basic instructions, but it basically is the same process as PS4 controller in the system settings area of Steam BPM / SteamOS.

**Comment by pogipants** [comment]
The client cannot natively support PS3 controllers as it is not a regular bluetooth device--PS4 has a 'normal' bluetooth mode. I have found help elsewhere, it seems this guy has compiled for sixpair and sixad into a deb. Now i can map my PS3 controller in SteamOS--maybe you could post this in your wiki since you are not actively supporting qtsixa anymore.

https://www.reddit.com/r/SteamOS/comments/1svnfx/ps3_controller_bluetooth/

**Comment by ProfessorKaos64** [comment]
No, it was patched recently. PS3 controllers are trusted now.

https://steamcommunity.com/groups/steamuniverse/discussions/1/412448158162767450/

**Comment by pogipants** [comment]
Not sure what that means, but i'll uninstall all the tools i mentioned and
see where it goes without it.

Justin Michel
paypal.me/pogipants
about.me/justinmichel
*juissy.com <http://juissy.com>*
*justinandkrissy.com <http://justinandkrissy.com>*
