### ISSUE TITLE
Include Kodi PVR addons

### ISSUE THREAD

**Issue by jazz1138** [ProfessorKaos64/SteamOS-Tools#92]
Any plans to include the kodi PVR add-ons in the repo? Most distributions include the option to install them individually e.g.

apt-get install kodi-pvr-tvheadend-hts kodi-pvr-vdr kodi-pvr-mythtv

See https://github.com/xbmc/xbmc/blob/master/docs/README.linux section 4.4 for build instructions.

**Comment by ProfessorKaos64** [comment]
Sure, I can add these. I will let you know when it is up in the repo.

**Comment by ProfessorKaos64** [comment]
I talked briefly to @wsnipex about this. The suggested way to to package this is to do so individually, rather than just specify this incorrectly in rules file for the Kodi debian build directory. I attempted to build mythtv from https://github.com/kodi-pvr/pvr.mythtv, but it seems to expect a certain cmake list 
```
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findkodi.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "kodi", but
  CMake did not find one.

  Could not find a package configuration file provided by "kodi" with any of
  the following names:

    kodiConfig.cmake
    kodi-config.cmake

  Add the installation prefix of "kodi" to CMAKE_PREFIX_PATH or set
  "kodi_DIR" to a directory containing one of the above files.  If "kodi"
  provides a separate development package or SDK, be sure it has been
  installed.
```
I took a look at the [Ubuntu PPA](https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=vivid) package for the same addon. The same error above occurs. Once I can figure out how that is done, I can automate a build of each pvr github repository and decrease maintenance overhead. At this time however, I can't seem unravel the process in which they are built without some help. I'll continue to look at this.

**Comment by ProfessorKaos64** [comment]
Is it not acceptable to install the addon zip files? I could build the addons from the upstream sources, but I think it will take a bit more work to make the deb packages from the knowledge I currently have. For example, it is easy to build the addon zip from [source](http://kodi.wiki/view/MythTV_PVR/BuildFromSource), but if you go to package/install it, the install locations go to to a [location](https://github.com/janbar/pvr.mythtv/blob/doityourself/debian/kodi-pvr-mythtv-dev.install) that the default install doesn't read from. 

What I could do, is rebuild the source from the PPA for the PVR addons only. This is not ideal, and may not work, but it's what I could give you for now.

**Comment by wsnipex** [comment]
see http://forum.kodi.tv/showthread.php?tid=232318&pid=2054777#pid2054777

**Comment by ProfessorKaos64** [comment]
@wsnipex , should I be build against your [mythtv pvr](https://github.com/kodi-pvr/pvr.mythtv/) repository, or the original [upstream](https://github.com/janbar/pvr.mythtv/)?

**Comment by wsnipex** [comment]
if you are building against kodi 15 then you need to use the addons Isengard branch.
And use the kodi-pvr repos

**Comment by ProfessorKaos64** [comment]
All good wsnipex, thank you. @jazz1138 , after some testing, i'll send a deb up the testing repo. If not mythtv, which addon would you first like to try before I continue on to the rest?

**Comment by ProfessorKaos64** [comment]
@jazz1138 , all pvr addons are built and in the libregeek repository. Please install any that you can and test. Otherwise, I will close this issue within a week or so.

**Comment by petroid** [comment]
iptvsimple add-on seems to be working including xmltv TV guide and channel logos.
Big thanks!

**Comment by ProfessorKaos64** [comment]
@petroid , thank you for the feedback, it really helps. I will give @jazz1138 sometime to response before closing this.
