### ISSUE TITLE
obs-studio - not working when returning to Steam

### ISSUE THREAD

**Issue by bstascavage** [ProfessorKaos64/SteamOS-Tools#99]
Maybe this is more of a troubleshooting thing...

I installed obs-studio via your scripts, and got it to stream my desktop fine.  However, when I click 'Return to Steam' it still is stuck recording the desktop.  I assume that this ha something to do with running it as the desktop user instead of the steam user?

**Comment by ProfessorKaos64** [comment]
You are correct. There isn't much currently I can do about this. At some point in the near future (when I have time between a bunch of things) I want to check out the command line options for make it launch as the steam user in SteamOS BPM. You won't be able to (as far as I know), just run it in desktop mode and have it record a completely different TTY line (which steamcompmgr runs on). I think (don't quote me) they run as TTY6 (desktop mode) and TTY7 (SteamOS BPM on the standalone compositor). 

I'll continue to see if there is a way to make it work with an obs-studio profile set to just record via a script. It may be tricky though.

**Comment by bstascavage** [comment]
I can investigate it this week and see if I notice something.  I appreciate your work for SteamOS so far, but unfortunately, in this state, OBS is more of a novelty than a practicality :(

**Comment by Ryochan7** [comment]
It is too bad that the option to record a different X display doesn't work properly in OBS. It seems to only capture for the last frame before OBS finishes writing the video file. As it stands, using OBS on SteamOS isn't very practical unless the steam user is logged into the Gnome session. Although, I don't use the proper SteamOS session often so having OBS available has been great for my configuration.

**Comment by egee-irl** [comment]
> I assume that this ha something to do with running it as the desktop user instead of the steam user?

This is exactly why and there's probably not much anyone can do about it. It's not necessarily an "issue" per se. Think about it, in an enterprise-like environment, user 1 can turn on a screen recorder and record user 2's desktop session? Sounds sketchy ;)

At any rate, your best bet would be to some how launch it from the SteamOS interface and then get back to your Steam library without closing Obs in the process. This may be a problem because SteamOS doesn't appear to be able to run more than two "games" (applications, really) at a time.

**Comment by ProfessorKaos64** [comment]
The only way I see that as possible, if if you could hack around the %command% with launcher options for the "game." I have found, as most have, that these are specific to the game, acting as a wrapper. There isn't a global "set" that I have seen that allows you to prelaunch things in this fashion.

**Comment by bstascavage** [comment]
This might be a dumb question, but why is there even a separate 'desktop' and 'steam' user?  I can't really think of any advantages, and I know that this has stopped other apps from working correctly.

**Comment by ProfessorKaos64** [comment]
If you want a desktop experience, you use something like Linux Mint, Fedora, and so on. Desktop usage is not the focus of SteamOS at all. It's main target upon starting up is to switch to steamos-session, powered by the standalone steamcompmgr. Nothing is to interfere with it, to my, or others tinkering determent. No system message from the OS, no annoying updaters, nothing is to get in it's way, and that is part of the console experience. For the intended user/user, desktop mode shouldn't be anything they even know about. Would I drop to a desktop on a PS4? No. Am I glad, I have a console experience that allows me to do so if I know what I am doing? Sure! For better or for worse, steamcompmgr is kind on the steamos-sesion.

**Comment by bstascavage** [comment]
I know what the point of the desktop is, and trust me, I think it is defeating the point whenever I have to drop to it for something.  I don't understand why the desktop is running under the 'desktop' user instead of the 'steam' user.  All it seems to do is cause issues like these.

I would consider keeping this issue open, at least to remind us to investigate OBS usage.  In it's current state OBS on SteamOS is pretty much a novelty, since it can't actually capture BPM running via the 'steam' user

**Comment by Ryochan7** [comment]
This issue isn't just due to SteamOS being set up to run desktop mode as a different user. As the steam user, I cannot capture video from separate X displays when one display is running the Gnome session as steam and another display is running an Openbox session as steam. I have also tried a similar type of setup on Xubuntu 14.04 and I can't get it working right there either.

As for launching apps outside of Steam's control, one way to do it is to use screen as a session manager. You would have to launch screen when you start a new X session and then create shortcuts to launch applications through that screen session so Steam does not see a launched process as a child process. That would actually allow an application to be launched from a Steam shortcut and keep the application running after returning to your Library.

I wrote about something like this a while ago. The post was about one way to use Mumble in SteamOS. The main issue after using screen is if you want to actually see the GUI at any point since applications usually rely on the Steam Overlay library in order to allow an application to be seen by steamcompmgr. I am not sure if manually injecting the STEAM_GAME atom would be enough for steamcompmgr to see the application if the overlay library is not loaded when launching an application.

https://steamcommunity.com/groups/steamuniverse/discussions/1/622954023419016739/

**Comment by Ryochan7** [comment]
Found a bad way to actually allow window switching in the SteamOS session. Even with that method, I could not get OBS to record gameplay. However, I was able to get SimpleScreenRecorder to work using the X display recording method.

https://youtu.be/kBoScO0DY6E

In theory, launching OBS or SimpleScreenRecorder into a screen session and then recording video footage in steamcompmgr is technically possible. However, it is terribly inconvenient and it would be better if someone were able to figure out a method to record a secondary X display using either program.

**Comment by ProfessorKaos64** [comment]
This is precisely why I record using a cheap-ish capture device. I also [record](https://github.com/ProfessorKaos64/SteamOS-Tools/wiki/Gameplay-recording) at times with ffmpeg using [this script](https://github.com/ProfessorKaos64/SteamOS-Tools/blob/brewmaster/scriptmodules/extra-pkgs.shinc#L141). Thanks for looking into it @Ryochan7 .

**Comment by ProfessorKaos64** [comment]
@bstascavage , obs-studio version 13.0 released upstream and built for this repository. Can you retest?
